Repository Roboy/roboy_memory, pull requests merged in 2018-08, with the labels that each got.

#46 Added SpecialPeople
  src/org/roboy/memory/util/Dictionary.java
Labels: DE, enhancement

#44 Feature logging
  pom.xml
  src/org/roboy/memory/util/MemoryLoggerInterface.java
Labels: DE, enhancement

#48 version fix
  pom.xml
Labels: bug

#49 CamelCase Is Not Supported BugFix --> Annoy Freddy for this
  src/org/roboy/memory/util/Dictionary.java
Labels: Hackathon, botboy, bug, enhancement
